language: php

php:
- 5.5

sudo: false

before_script:
  - composer install --prefer-source
  - nvm install 4

script:
  - composer test
  - npm install && npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
